### ISSUE TITLE
Kraken good accessibility - Completed

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/kraken-good-accessibility#1]
Enjoy your long weekend!!
@thatkidmadrid

**Comment by thatkidmadrid** [comment]
There are a few things that we quickly covered in class regarding the structure of the page and using articles that need to be addressed. You have a different article wrapping your header, div, and footer, when they could all be part of the same article. 
- `<article>` tags specify content that should make sense on their own ([w2 docs on articles](https://www.w3schools.com/tags/tag_article.asp)). Although you can argue that the header, main, and footer could make sense on their own for some edge cases, what makes the most sense in my opinion is to have them together in one article. 
  - Wrapping the secondary header that contains the current chapter and nav in an article may not make the most sense. It makes the most sense if it's next to the content of that chapter! I would put it inside the article that contains the div (I would give that the `role="main"` instead of the `<main>`; and instead of using a `<main>` this would be a good case to use an article.
  - then I would move the footer with the nav into the same article. This will create a more complete article (with a header-main-footer structure that we're used to seeing)
```
<body>
  <ul class="skip-links">...</ul> <!-- Stoked to see this! -->
  <header role="banner"></header>
  <article>
    <header>...(this contains the main navigation with the role="navigation")</header>
    <div role="main">...</div>
    <footer>(this is the navigation footer)</footer>
  </article>
  <footer role="contentinfo">...</footer>
</body>
```

In terms of the accessibility descriptions I think  you did a good job. 

I would be very careful with the `role="presentation"`. You actually don't want it in the figure because the figure isn't decoration. It is an image that is part of the chapter, so the only attribute it needs for accessibility is the alt attribute description.

If you can make the changes to the structure and remove the unnecessary presentation role, you can ignore any leftover styling issues and I'll pass the exercise and add the grade on LTW. Please let me know when you've made the changes

**Comment by emahadzimustafic** [comment]
Hi Christian, I've made the changes. Thanks!

**Comment by thatkidmadrid** [comment]
Great, I'll add the grade, but please be careful especially when writing written descriptions that the content makes sense. I think you meant to write 
> An image of the kraken grappling onto a sinking ship

but you only have

> An image of the kraken grappling onto a sinking

**Comment by emahadzimustafic** [comment]
Just fixed it! Must have missed that, thanks for letting me know.
